version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  database:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: boreproject
      POSTGRES_DB: boredb
    volumes:
      - timescale-data:/var/lib/postgresql/data

volumes:
  timescale-data: